language: perl
perl:
  - "5.18"
  #- "5.16"
  #- "5.14"
  #- "5.12"
  #- "5.10"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

before_install:
    - "bash ./travis_scripts/dependency_installs"

install:
    #This should solve problem installing Perl's DB_File & GraphViz
    - "sudo apt-get install libdb-dev graphviz libgd2-xpm-dev libxml2-dev 2>&1 | tail -n 4"
    #These are recommended or required Perl libraries
    - "cpanm GD 2>&1 | tail -n 1"
    - "cpanm HTML::TableExtract DBI Data::Stag DB_File 2>&1 | tail -n 1"
    - "cpanm DBD::mysql DBD::Pg DBD::SQLite 2>&1 | tail -n 1"
    - "cpanm Algorithm::Munkres Array::Compare Convert::Binary::C Error 2>&1 | tail -n 1"
    - "cpanm Graph SVG SVG::Graph GraphViz 2>&1 | tail -n 1"
    - "cpanm XML::DOM::XPath XML::Parser XML::Parser::PerlSAX 2>&1 | tail -n 1"
    - "cpanm XML::SAX XML::SAX::Writer XML::Simple XML::LibXML XML::Twig XML::Writer 2>&1 | tail -n 1"
    - "cpanm PostScript::TextBlock Set::Scalar Sort::Naturally YAML 2>&1 | tail -n 1"
    - "cpanm Math::Random SOAP::Lite Spreadsheet::ParseExcel 2>&1 | tail -n 1"
    - "cpanm Bio::Phylo 2>&1 | tail -n 1"
    - "export PERL5LIB=$( pwd )/travis_builds/Bio-Root/lib:$( pwd ):$PERL5LIB; cpanm Bio::ASN1::EntrezGene 2>&1 | tail -n 1"
    #This installs BioPerl itself:
    - "perl -I$( pwd )/travis_builds/Bio-Root/lib ./Build.PL --accept"

script:
    - "./Build test"

#TODO - send emails to bioperl-guts-l
notifications:
  email: false

# whitelist branches
branches:
  only:
    - master
